CaptchaRequest: Forgot to add FLAG_ACTIVITY_NEW_TASK to the STOP Intent
```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at pw.thedrhax.mosmetro.authenticator.CaptchaRequest.getResult(CaptchaRequest.java:90)
	at pw.thedrhax.mosmetro.authenticator.providers.MosMetroV2$8.run(MosMetroV2.java:277)
	at pw.thedrhax.mosmetro.authenticator.Provider.start(Provider.java:246)
	at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:205)
	at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:285)
```